pipeline:
  build:
    image: node:latest
    commands:
      - npm install
      - npm run build
      - npm run lint
  docker-testing:
    image: plugins/docker
    registry: registry.opentherapi.com:5000
    repo: registry.opentherapi.com:5000/opentherapi/opentherapi-profiles
    tags: [ testing ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: develop
      event: [push, tag, deployment]
  docker-production:
    image: plugins/docker
    registry: registry.opentherapi.com:5000
    repo: registry.opentherapi.com:5000/opentherapi/opentherapi-profiles
    tags: [ latest ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: [push, tag, deployment]
  deploy-testing:
    image: peloton/drone-rancher
    url: http://34.248.158.245:8080
    service: opentherapi-testing/profiles
    docker_image: registry.opentherapi.com:5000/opentherapi/opentherapi-profiles:testing
    secrets: [ rancher_access_key, rancher_secret_key ]
    when:
      branch: develop
      event: [push, tag, deployment]
